### ISSUE TITLE
Calamari installation hints

### ISSUE THREAD

**Issue by jbarth-ubhd** [qurator-spk/train-calamari-gt4histocr#6]
Dear reader,
I would suggest adding the following installation hints:

```
virtualenv -p python3 calamari-0.3.5_venv
source calamari-0.3.5_venv/bin/activate
pip install calamari_ocr==v0.3.5
pip install tensorflow==v1.15.0   # v2.x does not work
```

**Comment by mikegerber** [comment]
This repository mainly serves as documentation of the provenance of the model published at https://qurator-data.de/calamari-models/, not as the definitive guide to training such a model. 

I'd also argue that someone who would rather train a new model than just use the ready-made one, should be able to set-up a virtualenv and use `pip install -r requirements.txt` etc. So I'm not including any more installation hints to reduce maintenance work on the documentation, I hope you understand.

I did however update [README.md](https://github.com/qurator-spk/train-calamari-gt4histocr/blob/master/README.md) to reflect this. 👍
